### ISSUE TITLE
Possible Feature: Add Torrents to Seedbox

### ISSUE THREAD

**Issue by ricksee** [Kylart/KawAnime#11]
Is it possible to add seedbox server integration for when one wants to watch their shows on the go like through Plex or something?

**Comment by Kylart** [comment]
I have some feature ideas for distant servers and one of them is to ability to connect to a distant server, it would allow to start torrents directly on a distant server.
Currently you can hit that "Magnets" switch in the downloader page (or save it in your settings too) to get a list of magnets that is pastable magnets to feed your server with.
 
That being said, this is a very advanced feature that will not be available so shortly. Also, there is the possibility that while trying to implement it, I feel like it is too complicated or anything.
