### ISSUE TITLE
Can you enable yarn run dist:linux to also build the deb and all the relevant stuff in /usr/share?

### ISSUE THREAD

**Issue by SolarAquarion** [Kylart/KawAnime#16]

**Comment by Kylart** [comment]
So actually you just want me to enable `yarn` on `KawAnime` right?

**Comment by xdk78** [comment]
Using two package mangers is not good IMO

**Comment by SolarAquarion** [comment]
well, I did yarn and it worked, so am I supposed to use npm run dist:linux?

**Comment by Kylart** [comment]
You can actually use `yarn run dist:linux probably`. I tried and it works for me so tell me if it does not work on your side.
I'm going to add a `yarn.lock` file though.

**Comment by Kylart** [comment]
You can probably run `yarn run dist:linux`. I tried and it works on my end. Please try and tell me.
I'll add a `yarn.lock` file though

**Comment by Kylart** [comment]
I added a `yarn.lock` file recently. Also, as yarn is perfectly working on my end, I'll close this issue. Feel free to comment and tag me again if any problem occurs!

**Comment by SolarAquarion** [comment]
It doesn't build a debian only a AppImage when I do dist:linux

**Comment by Kylart** [comment]
You are actually right, it seems `dist:linux` builds only the AppImage atm while when I publish I build both `.deb` and `.AppImage`.
 
I'm going to set `dist:linux` to build `.deb` right away!
