### ISSUE TITLE
Anime tracking integration

### ISSUE THREAD

**Issue by xdk78** [Kylart/KawAnime#17]
Myanimelist and Kitsu integrated into the app with features like auto updatee watched episodes etc

**Comment by Kylart** [comment]
Yea I definitely have to do something about this. I've been thinking about it for quite a time now so I'm probably going to work on this very soon!

**Comment by JuanjoSalvador** [comment]
Check [anitomy-js](https://www.npmjs.com/package/anitomy-js) and another Erengy/Taiga's modules, there is some wrappers for JS and it would be cool for this feature.

**Comment by Kylart** [comment]
So there are two things here: 
1. MyAnimeList / Kitsu integration.
2. Auto-update when watching.

The first one is being worked on actively as of right now and should be available very soon. It'll allow to enter animes is your MyAnimeList.net watch lists (scores and stuff are also included). Kitsu integration might follow up too.

Auto-update when watching is a really nice feature I'd love to work on but for this I need to finish the first point first 😄 .

As of `anitomy`. I have my eyes on this for prolly a month now especially to allow to download every single torrent from `nyaa` (and maybe others). It would allow to make an in-app nyaa browser for example!

Lots and lots of things to do! 😃

**Comment by JuanjoSalvador** [comment]
Just make us a sign if you need help :wink:

**Comment by Kylart** [comment]
Help is always appreciated 😄 

I am currently working on a Discord server to have better interaction with people that'd like to help!
