### ISSUE TITLE
[Feature request] Implement anime season's following state and filters 

### ISSUE THREAD

**Issue by hanesh** [Kylart/KawAnime#19]
Are there any plans to add streaming instead of just downloading? Whether this be through torrents or through sites like animerush, kissanime, or 9anime.
Also, I haven't really tried this out yet(so not sure if this is a feature)... But is there any way to show missing anime from seasons?

**Comment by JuanjoSalvador** [comment]
Duplicated #18

**Comment by Kylart** [comment]
> Also, I haven't really tried this out yet(so not sure if this is a feature)... But is there any way to show missing anime from seasons?

Do you mean the shows that are not showed in the `seasons` section but which are still seasonal shows. So this season's anime that are missed out by _KawAnime_?

**Comment by hanesh** [comment]
Uh no, I meant anime that aren't in your watched list.

**Comment by Kylart** [comment]
I am not sure to fully understand...

Yet, in the next version (actually it's already on `master`), there is a feature allowing to know if an anime in the `releases` page are in your `watch list` or your `watching` list!

**Comment by hanesh** [comment]
I mean like on mal you have a completed list. I wanted an option to check for missing anime(anime that you haven't watched during the selected season and to possibly filter by a rounded mal score so that you can find anime you might be interested in when you have a 1000+ list)

**Comment by Kylart** [comment]
Ohhhhhhh

Yea no it's not possible at the moment though it definitely is a great idea! I'll definitely work on that once I'm done with the MAL integration!
