### ISSUE TITLE
Missing symbols

### ISSUE THREAD

**Issue by foodcube** [Kylart/KawAnime#22]
The AUR install does not seem to list required fonts as dependencies. As such, missing symbols are replaced by empty boxes. Which font do I need to install to fix this?

**Comment by Kylart** [comment]
Hello,

For the AUR, I do believe @SolarAquarion is the one that made it.

The font used for the japanese font is [this one](https://github.com/Kylart/KawAnime/blob/master/assets/App.vue#L238). So i guess maybe you need one of those (?) :
* https://www.archlinux.org/packages/?name=otf-ipafont
* https://www.archlinux.org/packages/?name=ttf-hanazono

**Comment by foodcube** [comment]
Thank you. That seems to have resolved it.
