### ISSUE TITLE
XviD option alongside standard resolution

### ISSUE THREAD

**Issue by BoneFillet** [Kylart/KawAnime#23]
My plex server requires .srt or hardcoded subtitles, and the .ass subtitles requires transcoding on top of the standard streaming to a client.

**Comment by BoneFillet** [comment]
Hope this isn't too big of an option to implement given resolution options are already here!

**Comment by Kylart** [comment]
If I understand well your problem, you need to get the subtitles out of the downloaded episode right?

If this is it, then it will probably be done when I'll work on #18 I guess.

**Comment by Kylart** [comment]
Ok so after working on the streaming feature and actually implemented that "postprocessing" to the .ass subtitles, I do think that what's ask goes beyong what KawAnime should do.

What is possible is to extract that .ass title to a separate file yet KawAnime won't convert this file to a .srt nor hardcode the video as this would require external dependencies like `ffmpeg`.

KawAnime now has (not released yet) a in-app player able to parse and handle .ass substiles as well as .srt subtitles so maybe that helps?
