### ISSUE TITLE
Telegram chat

### ISSUE THREAD

**Issue by BakasuraRCE** [Kylart/KawAnime#25]
I have seen that many projects are now integrating Telegram as an effective means of communication between users and developers.

Examples:
https://github.com/radare/radare2
https://github.com/x64dbg/x64dbg

It could be a good idea for this project too.

Thanks for your time

**Comment by Kylart** [comment]
I have never used Telegram ever but I'm not against it.

But I'm not sure about some things:
  - What's the point of having 2 ways of chatting? I think some information would get lost.
  - Currently I am the only developer on this project and the Discord chat isn't that active either. Wouldn't it be overkill to have 2 chats?

**Comment by BakasuraRCE** [comment]
Well, I've never used Discord,

But some features of Telegram are:
 - Multi Platform (u can run inside a rock, literally)
 - Log all media content
 - Can add bots
 - Many group moderation options
 - Tons of Kawaii Stickers (haha, well, i like it)
 - Privacy of your cellphone number
 - Require cellphone number have one account
 - Polls, Games.
 - Easy send any media content
 - Calls

And has been successful in the other projects mentioned (that are big)

I agree that there should only be a means of communication via chat, well, you could try and decide.

PD: My intention is not to discredit Discord, I just want to introduce you to a tool that I have seen with great success in other projects.

Preview:
![image](https://user-images.githubusercontent.com/26231582/34637203-d26e6fd6-f27e-11e7-8848-a9000df89cb6.png)

**Comment by Kylart** [comment]
I will check it then 😄 

Actually almost all the features you listed are included in Discord. I'll check it for a bit so I can see what's best. I've seen some major successful projects work with Discord and I'm using it everyday and that's simply why I chose it.

**Comment by JuanjoSalvador** [comment]
Discord seems fine. In fact, all the good things we could need, are on Discord and Telegram. So, if we have a discord server, why create another way?

**Comment by Kylart** [comment]
Yep actually I think we're gonna stay on Discord for now 😄
