### ISSUE TITLE
Proxy configuration support

### ISSUE THREAD

**Issue by BakasuraRCE** [Kylart/KawAnime#28]
would be nice have option to config proxy settings like Firefox:

![image](https://user-images.githubusercontent.com/26231582/34646018-5d1d82e6-f32b-11e7-99df-409d11f40215.png)

This is because some users can be using some particular network configuration and would need pass the application through its proxy or not.

**Comment by Kylart** [comment]
So I've been thinking a lot about proxies.

As for the current version, I do think this is not needed as the app actually only delivers links and I'm not sure if a proxy would really be needed in there. I don't think many networks are blocking myanimelist.net and nyaa.

If KawAnime could already include a torrent client, I would understand the need. 

*Yet*, I do believe that a proxy should be used in the whole OS and not only in an app or another. A proxy is more useful when configured system widely.

Anyway, I don't think this question is really important unless KawAnime features an in-app torrent client.
