### ISSUE TITLE
[Website] KawAnime Git version in AUR

### ISSUE THREAD

**Issue by BakasuraRCE** [Kylart/KawAnime#29]
I have published the git version in AUR so that users can keep up with the latest changes of each commit:

https://aur.archlinux.org/packages/kawanime-git/

**Comment by Kylart** [comment]
Thank you! I'll try to show AUR links on the websites whenever I'll rework it a bit 😄

**Comment by Kylart** [comment]
This is getting quite outdated, I'll close it.
