### ISSUE TITLE
[Feature request] Keep file to preferred folder after stream

### ISSUE THREAD

**Issue by DemonRem** [Kylart/KawAnime#33]
when I downloading the anime torrent few of the torrent are stuck since 1 day in connecting to peers

any idea?

---------------------------------

also I have an Idea to improve the software , if you know popcorn time , when you watch the movie it's download the movie as mp4 directly to Download folder the movie while you watch the movie , it's can be a nice feature for the software you may look at the code of popcorn time.

https://github.com/popcorn-official/popcorn-desktop

**Comment by DeltaEvo** [comment]
@DemonRem this is the problem with torrents, there is not always seeders for the file, you can't do anything with this

And for popcorntime, I didn't know about this feature, but I don't know if it's really usefull because I don't watch an anime twice :joy:

**Comment by DemonRem** [comment]
@DeltaEvo 

but still can be good option ;)

**Comment by Kylart** [comment]
> when I downloading the anime torrent few of the torrent are stuck since 1 day in connecting to peers
 
This I cannot do anything about as as @DeltaEvo said, it's a torrent-related problem.

> also I have an Idea to improve the software , if you know popcorn time , when you watch the movie it's download the movie as mp4 directly to Download folder the movie while you watch the movie , it's can be a nice feature for the software you may look at the code of popcorn time.
 
This is something I already thought about and that I'll try to implement as a setting when I'll be done with the torrent store (in-app torrent client) as it's not something that will be used by everyone (if people only want to stream, they might not want to keep the file).
 
Please though, do understand that this _might_ take time to be released in actual production.

**Comment by DemonRem** [comment]
@Kylart 

i understand , but thank for the feedback i really appreciate it

**Comment by DemonRem** [comment]
@Kylart ,

thank for adding this to the idea label <3

**Comment by Kylart** [comment]
Solved on `remake` branch.
