### ISSUE TITLE
[Feature request] Multi-language

### ISSUE THREAD

**Issue by xwellingtonx** [Kylart/KawAnime#38]
I think it's a good idea we have multi-language support for interfaces. Now with anime description we can translate it with google why it will be difficult to find a database with descriptions in several languages.

**Comment by leandrodlm** [comment]
Let me know if you guys need an Portuguese Translator... i will watch this project.

**Comment by Kylart** [comment]
Sorry, I probably won't be able to do this as it would require too many things and I can't translate text accurately for free.

**Comment by cartals** [comment]
Let me know if you want TR translation.
