### ISSUE TITLE
[Feature request] Change Theme and Waifu Images

### ISSUE THREAD

**Issue by xwellingtonx** [Kylart/KawAnime#39]
It would be interesting to let each user use the theme they like or favorite characters in the application.

**Comment by Kylart** [comment]
Ok so an update on this.

There now is a dark / white theme available (though the white theme does feel really ugly to me).

Upon redesigning the app, I removed all the waifu images in the nav bar and stuff. There are clips but those are not customisable as they are part of the app.

Hence I'm closing this issue as it was partially solved and the part that was not solved does not exist anymore.
