### ISSUE TITLE
[Feature Request] Add confirmation dialogue before initiating download.

### ISSUE THREAD

**Issue by MagiOC** [Kylart/KawAnime#42]
I just started using KawAnime on mac earlier today. I got barraged by download location boxes(47 of them) when using the downloader to download Boku No Hero Academia episodes after I toggled "Get Magnets" just to see what would happen. This caused my laptop to slow down to a crawl. With no way to stop the oncoming download boxes I was forced to shutdown my pc.

Suggestion to put in a dialogue box saying something like "This will initiate X downloads, are you sure"? with confirmation /cancel buttons for downloads with "Get Magnets" toggled off.

**Comment by Kylart** [comment]
I plan on removing this feature anyway, "Get magnets" should always be turned on.

**Comment by MagiOC** [comment]
Oh neat thanks for the quick response I'll look forward to future releases.
