### ISSUE TITLE
All anime????

### ISSUE THREAD

**Issue by Lochnessmonster925** [Kylart/KawAnime#45]
I've been looking for saiki kusuo psi nan season 2 but there's nothing :-((((( can this app really stream and download all anime or just some few selected animes?

**Comment by Kylart** [comment]
So here's the deal.

KawAnime works with fansubs, default one being [HorribleSubs](https://horriblesubs.info). When you look at some anime, the app is gonna look for it in the releases of this fansub.

Being the case of Saiki Kusuo and HorribleSubs. It seems that HorribleSubs did not "subbed" the second season of Saiki Kusuo. Also, looking at the available subbed releases for this season 2, it seems that not many fansubs worked on saiki kusuo Season 2.

Now I'd feel bad leaving you with nothing to watch and I planned this case when I worked on that streaming. Here's what you _can_ do:
1. [Make a quick search on nyaa.si](https://nyaa.si/?f=0&c=0_0&q=Saiki+kusuo+S2).
2. Copy the magnet link or download the torrent files of whatever episode you wanna watch (batch won't work if you try to stream them).
3. Simply paste the magnet link into the app of drag-drop the torrent file in the app.
4. Enjoy!
