### ISSUE TITLE
New Source

### ISSUE THREAD

**Issue by DemonRem** [Kylart/KawAnime#47]
there is a source i see with sesson like Prison School at last with one episode what other source doesn't you may look it here

UPDATE : Streaming , it's take data from different Source's it's can be good to the software since KawAnime dont find that Prison School: Mad Wax: stream 
what i found there.
http://watchanime.info/prison-school-mad-wax/

**Comment by Kylart** [comment]
As long as you have a torrent file or a magnet link, you can stream it in KawAnime. No source needed at the moment.

KawAnime offers magnet links for most of the anime but if not available, you can always simply paste the magnet link into the app or drag & drop a torrent file or a video file into the app to watch it.
