### ISSUE TITLE
[Feature Request] Thumbnails for Watch List

### ISSUE THREAD

**Issue by urabe213** [Kylart/KawAnime#51]
If it isn't too much, it would be great if there was an option to enable/disable thumbnails in the watch list page. I just like browsing lists that have pictures :) Also, an option, like in windows 10 file explorer, where you can adjust the thumbnail/icon size.

Thanks! Really love your work. Glad I found out about this.

**Comment by Kylart** [comment]
Hello,

First, thank you for the kind words, I'm always glad to hear people enjoy the app!

So usually the app has two `watch lists` page: local and MAL. MAL has thumbnails but the API is down actually so no third-party can access those data.

As for your issue, it's talking about the local watch list page. I wish I could add thumbnail to those but it's really tricky as those would come from MAL (for now) and MAL has things in place in order not to be spammed by third-party apps. Usually, local watch lists have dozens of entries and it would spam MAL.

But fear not, I will try to find new ways of getting those, it's annoying to have to _search_ for the information only to find that you just forgot the anime graphics or so.

I cannot guaranty this will be in the next release but be sure I'm working hard to fulfil feature requests that are  feasible and this one probably is!
