### ISSUE TITLE
[MAL] Ability to import to local lists

### ISSUE THREAD

**Issue by escobera** [Kylart/KawAnime#52]
I'm getting this error while trying to connect to myanimelist, tried the same login/pass directly on mal and it worked. My profile is set to public.

**Comment by Kylart** [comment]
This is simply because MAL API has been down for _months_ hence doesn't allow third-party apps to access their data.

More details on why this is down [here](https://github.com/erengy/taiga/issues/588).

I'm sorry I can't help much on this.

**Comment by FighterBoyZ** [comment]
Can you add a way to transfer your lists somehow? Maybe as an csv file?

**Comment by jgarnierVoodoo** [comment]
Do you mean the local lists ?

**Comment by Kylart** [comment]
Do you mean local lists ?

**Comment by FighterBoyZ** [comment]
Yeah. Would it be possible?

**Comment by Kylart** [comment]
I mean, of course. Though you already can have a JSON file with your local lists in it. For this, simply _copy_ the file at `/Users/<YOUR_USERNAME>/.KawAnime/lists.json`.

I'll add an `Export` button which will be available in the next release along the new design!

**Comment by FighterBoyZ** [comment]
Sorry, I meant importing to local list. Might have worded that wrong. I guess export button would be useful also.

**Comment by Kylart** [comment]
Can do along the export button though where would you import your data from (File format, source, ...) ?

**Comment by FighterBoyZ** [comment]
I was wondering if I could import my MAL list. Still haven't figured out how to do that. I guess I could import as xml.

**Comment by Kylart** [comment]
Mmmmh I don't think MAL offers a `Export my list as XML` feature or at least I don't know of it. An import list feature would be really long to setup for each website. If I was to make it, I would probably make it for KawAnime. Like export your lists to import it on another computer which would be useful for people actively using the app and changing their compputer / setup.

**Comment by Akamaru** [comment]
Hi, you can export your list as XML here: https://myanimelist.net/panel.php?go=export

**Comment by Kylart** [comment]
You're right !

I wonder if that would be a nice idea, I'd rather have the app automatically import your MAL data when it can load them.

Tbh, I can't (also I really don't want to) do much things MAL related since the API is down for months now and no one knows when it will come back or if it's coming back anyway.

**Comment by Kylart** [comment]
This is now possible with c362ce0ed97525bbf19d289cc66fdcf630588cb0
