### ISSUE TITLE
500 | Internal Server Error ReferenceError: window is not defined

### ISSUE THREAD

**Issue by bajki** [Kylart/KawAnime#57]
Hi i want to use vuex-persistedstate but im getting this error.

500 | Internal Server Error
ReferenceError: window is not defined
    at module.exports (KawAnime-master/node_modules/vuex-persistedstate/dist/vuex-persistedstate.js:1:398)

Is there any fix for this?

**Comment by Kylart** [comment]
KawAnime is a server-side rendered app, similar to how a nuxt app is working. Thus, in the server context, window is not defined and you get this error.

You can fix that by doing something similar to [this file](https://github.com/Kylart/KawAnime/blob/master/app/web/mixins/video/ass/tags.js#L5).

```javascript
let Velocity = null

if (typeof window !== 'undefined') Velocity = require('velocity-animate').default
```
