### ISSUE TITLE
[Feature Request]Download Anime in background

### ISSUE THREAD

**Issue by DemonRem** [Kylart/KawAnime#58]
simply like popcorn time doing that he download the tv show as long the show on watching and internet connected "streaming download"

**Comment by Kylart** [comment]
Yes this one is planned and I'm gonna work on it in the following days 😄

**Comment by Kylart** [comment]
Alright so that won't be in background like Netflix or Popcorn time do, the player will simply start the next relevant episode for you to watch as soon as the one currently playing is done playing.

**Comment by Kylart** [comment]
This behaviour is implemented on the remake branch so I'm closing this issue.
