### ISSUE TITLE
 appimage segfault on solus os

### ISSUE THREAD

**Issue by Lukaboot** [Kylart/KawAnime#60]
@uwu ~/Downloads $ ./KawAnime-0.3.1-x86_64.AppImage 
Segmentation fault

Installing with npm install works fine, and then running in dev.

**Comment by Kylart** [comment]
What happens if you try to build your own AppImage ? 

```shell
$ git checkout v0.3.1
$ rm -rf node_modules package-lock.json
$ npm install && npm run dist:linux 
```

Your .appImage should be in the `dist` folder.

**Comment by Kylart** [comment]
I'm closing this issue as no answer has been given back.

If you encounter this problem, please feel free to comment and I'll reopen.
