### ISSUE TITLE
Stupid Developer! Delete the fking tracker script.

### ISSUE THREAD

**Issue by daghrtjuursy34** [Kylart/KawAnime#66]
Why in the fuck would you even include a tracker/analytics script in this. You faggot.

**Comment by ParadoxOrigins** [comment]
What's wrong with you

**Comment by Kylart** [comment]
I guess ignorance paid me a visit this month, how lucky!

Bad manners apart, you can simply opt out of the analytics events as shown here, simply uncheck that and you'll be fine.

![Capture](https://user-images.githubusercontent.com/18316666/67150015-7c003680-f2b2-11e9-8b91-a25e2294529c.PNG)

As for your question,
> Why in the fuck would you even include a tracker/analytics script in this.

The answer is to simple know how many users I have. There is no other event than `App opens` that are handled.
