### ISSUE TITLE
Kitsu.io

### ISSUE THREAD

**Issue by WeCode2Gether** [Kylart/KawAnime#69]
After logging in, i still can't seem to find my list. I hope a fix will be provided asap.

**Comment by Kylart** [comment]
Can you please give me some details on what exactly did you do and your OS?

**Comment by unholyN1** [comment]
I am also unable to view any list added when linking my kitsu.io account in settings and logging in. On the kitsu.io list tab I only see "no data available" and the refresh button does nothing. Restarting application or trying to relogin does not change anything.
On windows using prebuilt exe package from kawanime.com
