### ISSUE TITLE
Anime auto track does not work.

### ISSUE THREAD

**Issue by cartals** [Kylart/KawAnime#70]
Hi, i am using Arch linux. Installed kawanime by aur, Wrote my Anilist nickname and clicked register and i authorized it also restarted. When i click my library and chose an anime, auto tracking does not work. (vlc for animu watching.)

**Comment by Kylart** [comment]
Sadly, Anime auto-tracking can be enabled only with the local player for now. There are two reasons for this choice:

1. If the file is played with an external player, KawAnime has no way to know if you really watched it or missclicked it for any reason. To enable something alike, it would be required to make a custom plugin for each well known player to tell KawAnime that the file was indeed played.
2. It would be troublesome for people that already have plugins linked to their video player, it could cause problems during the updates.

Now for the solutions you have for this:
* Open the file inside the KawAnime's player and close it right afterwards which is troublesome but will enable auto-tracking
* Install (or make?) a plugin that allows you to auto-track your anime history with your video player. There are several out there for the most well known video players (e.g. for MacOS: [Hachidori](https://malupdaterosx.moe/hachidori/)) 
* Obviously you can also edit the entry every time in the according tab but that's not really auto-tracking...

I am sorry this is not available for external players for now. Next release will embed a real MPV player so the in-app player will be much better than it is today.

If you have any other idea on how to tackle this problem, feel free to tell me here or on Discord though!
