### ISSUE TITLE
libstdc++.so.6: version `GLIBCXX_3.4.26' not found

### ISSUE THREAD

**Issue by Ooggle** [Kylart/KawAnime#72]
Hello,

I am facing some issue when i try to launch the AppImage version of the app (it do the same with the .deb)
I'm using Debian 10 and this is the error :

![2020-04-01-034257_1039x510](https://user-images.githubusercontent.com/33269056/78090729-33a18480-73cb-11ea-8c26-58e3a9d68fe8.png)

All my packages are up to date, i hope you can do something about that,

Thanks !

**Comment by Kylart** [comment]
Hello,

Did you build the app yourself from the dev branch by any chance?

**Comment by Ooggle** [comment]
Hi, yeah but it do the same.

**Comment by Kylart** [comment]
Alright,

At the moment, only the `master` branch is safe to build and ship for all platforms.

The others branches are not safe to build and ship. You should only be able to `npm run dev` on most platform.

**Comment by Ooggle** [comment]
Ok so i managed to build the app from the main repo with the following :
```
git clone --single-branch --branch master https://github.com/Kylart/KawAnime.git && cd KawAnime
npm i
npm run dist:linux
cd dist
./KawAnime 0.4.2.AppImage
```
It show the message to add the shortcut like on the dev version then there is a segfault (see screen).

![2020-04-01-175648_480x59](https://user-images.githubusercontent.com/33269056/78158967-368b8c00-7442-11ea-92ed-1ae8133cb063.png)

I also tested by installing the .deb but it end with a segfault too. (i have installed all the dependencies of course)
Tell me if you need samples or something else.

**Comment by Kylart** [comment]
[Do this AppImage work?](https://github.com/Kylart/KawAnime/releases/download/v0.4.2/KawAnime-0.4.2-x86_64.AppImage)

**Comment by Ooggle** [comment]
No, It do the same error message that at the beginning.
I'm going to create a Debian VM to see if it's me or not, doens't want to take your time for nothing if it's the case.

I will reply here when i get the result.

**Comment by Ooggle** [comment]
So nothing change when i try to launch it from the VM, there is exactly the same error.
Using Debian 10, everything up to date.

**Comment by Kylart** [comment]
Alright, I tried on a fresh Debian 10 as well.
Try install `g++` package, it kinda worked for me

**Comment by Ooggle** [comment]
Hmmm still don't work for me since i already have it. I close the issue cause it seems that i'm the only one that have this problem, perhaps i do something bad...
