### ISSUE TITLE
Play button is inconsistent? Video stops playing?

### ISSUE THREAD

**Issue by alfronzo** [Kylart/KawAnime#75]
On the KawAnime desktop app for Windows 10, I search an anime I want to watch and press the triangle play button. about 90% of the time, the button doesn't work so I have to refresh or restart the app multiple times. Other times I have to click it multiple times to play the episode. When I am watching episodes, it buffers at the exact same spot somewhere random in the episode. The buffering doesn't stop, and when I try restarting KawAnime, it stops at the same place again. What could be the issues?

**Comment by Kylart** [comment]
Alright, I'm sorry but I am going explain exactly what's happening here.

When you press the play button, the app will try to load in the torrent link to that episode. I must say there is a lack of load ing animation, this will be added eventually. The video player will appear only when the metadata of the video are loaded in.  this means that if, the app cannot load anything from that torrent, it will wait until it has to show the video player.

I will not talk about how torrents work in details here. Basically, you are probably trying to watch a torrent that has not a lot a seeders available for you, that is, people sharing this torrent.

Refreshing or restarting the app will not change anything to that, I'm sorry. A loading screen would be all I could do.

If you want to watch older anime by streaming, which probably don't have that many seeders, I recommend you try finding batches on [nyaa](https://nyaa.si) or maybe you can find them on twist.moe.
