### ISSUE TITLE
kawanime.com security errors and privacy warnings

### ISSUE THREAD

**Issue by RioNight** [Kylart/KawAnime#91]
uBlock Origin displays a Page Blocked warning like this:
![image](https://github.com/Kylart/KawAnime/assets/58403689/f3c1e31d-9d5b-497d-a2d2-a92a5a883d43)

Then, after clicking "Proceed", the browser displays this Privacy error page:
![image](https://github.com/Kylart/KawAnime/assets/58403689/81ffbf35-fdf9-4da4-84f3-eb96d9604155)

After a few more hoops, I finally land on a fake McAfee page.

Can the official site's security be improved, or removed from the GitHub page so that users no longer click on it? It would be dangerous if left like this.

**Comment by Kylart** [comment]
I do not own the kawanime.com domain anymore so sadly there is nothing I can do here. I'll remove the references to the website from Github though.
